### ISSUE TITLE
ArrayIndexOutOfBoundsException when adding byte arrays to LargeList

### ISSUE THREAD

**Issue by ernisv** [aerospike/aerospike-helper#20]
When trying to add arbitrary byte arrays to LargeList, following exception occurs.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 118142
        at com.aerospike.client.command.Buffer.stringToUtf8(Buffer.java:195)
        at com.aerospike.client.Value$StringValue.write(Value.java:574)
        at com.aerospike.client.Key.computeDigest(Key.java:315)
        at com.aerospike.client.Key.<init>(Key.java:94)
        at com.aerospike.helper.collections.LargeList.makeSubKey(LargeList.java:88)
        at com.aerospike.helper.collections.LargeList.add(LargeList.java:182)

**Comment by ernisv** [comment]
https://github.com/aerospike/aerospike-helper/pull/21
