### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by mikkazan** [aerospike/aerospike-helper#4]
Not sure if this project is still alive. I've downloaded the aerospike aerospike-jdbc-0.2.3.jar from Aerospike site and now I have an issue connecting to the Aerospike database using Squirrel SQL and jdbc.
The issue started after I created indexes on my sets. Prior to that I was able to connect to the database.
My application fails to connect as well

Here is the stack trace

Caused by: java.sql.SQLException: [Aerospike][JDBC](11380) Null pointer exception.
	at java.util.TreeMap.compare(TreeMap.java:1290)
	at java.util.TreeMap.put(TreeMap.java:538)
	at com.aerospike.helper.query.QueryEngine.refreshIndexes(QueryEngine.java:515)
	at com.aerospike.helper.query.QueryEngine.refreshCluster(QueryEngine.java:438)
	at com.aerospike.helper.query.QueryEngine.setClient(QueryEngine.java:117)
	at com.aerospike.helper.query.QueryEngine.<init>(QueryEngine.java:104)
	at com.aerospike.jdbc.ASConnection.connect(ASConnection.java:214)
	at com.simba.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.simba.jdbc.common.AbstractDriver.connect(Unknown Source)
	at net.sourceforge.squirrel_sql.fw.sql.SQLDriverManager.getConnection(SQLDriverManager.java:133)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:167)
	... 7 more
Caused by: java.lang.NullPointerException
	... 18 more

Also by comparing the code of aerospike-jdbc on my local and what is here in github I noticed that here lines do not match. 
Please help me out

If I use pure Java connector in my code then I'm able to select data out of the sets.

**Comment by mikkazan** [comment]
Also there is thread on Aerospike forum regarding the same issue
https://discuss.aerospike.com/t/aerospike-jdbc-connector-is-not-working/2820
